environment:
  global:
    PROJECT_NAME: actix
  matrix:
    # Stable channel
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH = 'C:\msys64\mingw64\bin;C:\msys64\usr\bin;$Env:PATH'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH = 'C:\msys64\mingw32\bin;C:\msys64\usr\bin;$Env:PATH'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - git submodule update --init --recursive

# 'cargo test' takes care of building for us, so disable Appveyor's build stage.
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build
